spring.application.name=shareBazarBackend
jwt.secret=MySuperSecureJWTSecretKeyThatIsDefinitelyMoreThan32CharactersLong123
jwt.expiration=3600000

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yojehjkoshmksavjmewi
spring.datasource.password=0V0MjR2qU8CAxiw3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect