server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
jwt.secret=mysupersecretkeymysupersecretkey123
# Enable auto routing via service name
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=share-service
spring.cloud.gateway.routes[1].uri=lb://company-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/shares/**
 
spring.cloud.gateway.routes[2].id=portfolio-service
spring.cloud.gateway.routes[2].uri=lb://portfolio-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/trade/**

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true